#pragma once
#include <array>

namespace MinPhaseTaps {
constexpr std::array<double, 301> HB63_test_min = {
  nan, nan, nan, nan, nan, nan, 
  nan, nan, nan, nan, nan, nan, 
  nan, nan, nan, nan, nan, nan, 
  nan, nan, nan, nan, nan, nan, 
  nan, nan, nan, nan, nan, nan, 
  nan, nan, nan, nan, nan, nan, 
  nan, nan, nan, nan, nan, nan, 
  nan, nan, nan, nan, nan, nan, 
  nan, nan, nan, nan, nan, nan, 
  nan, nan, nan, nan, nan, nan, 
  nan, nan, nan, nan, nan, nan, 
  nan, nan, nan, nan, nan, nan, 
  nan, nan, nan, nan, nan, nan, 
  nan, nan, nan, nan, nan, nan, 
  nan, nan, nan, nan, nan, nan, 
  nan, nan, nan, nan, nan, nan, 
  nan, nan, nan, nan, nan, nan, 
  nan, nan, nan, nan, nan, nan, 
  nan, nan, nan, nan, nan, nan, 
  nan, nan, nan, nan, nan, nan, 
  nan, nan, nan, nan, nan, nan, 
  nan, nan, nan, nan, nan, nan, 
  nan, nan, nan, nan, nan, nan, 
  nan, nan, nan, nan, nan, nan, 
  nan, nan, nan, nan, nan, nan, 
  nan, nan, nan, nan, nan, nan, 
  nan, nan, nan, nan, nan, nan, 
  nan, nan, nan, nan, nan, nan, 
  nan, nan, nan, nan, nan, nan, 
  nan, nan, nan, nan, nan, nan, 
  nan, nan, nan, nan, nan, nan, 
  nan, nan, nan, nan, nan, nan, 
  nan, nan, nan, nan, nan, nan, 
  nan, nan, nan, nan, nan, nan, 
  nan, nan, nan, nan, nan, nan, 
  nan, nan, nan, nan, nan, nan, 
  nan, nan, nan, nan, nan, nan, 
  nan, nan, nan, nan, nan, nan, 
  nan, nan, nan, nan, nan, nan, 
  nan, nan, nan, nan, nan, nan, 
  nan, nan, nan, nan, nan, nan, 
  nan, nan, nan, nan, nan, nan, 
  nan, nan, nan, nan, nan, nan, 
  nan, nan, nan, nan, nan, nan, 
  nan, nan, nan, nan, nan, nan, 
  nan, nan, nan, nan, nan, nan, 
  nan, nan, nan, nan, nan, nan, 
  nan, nan, nan, nan, nan, nan, 
  nan, nan, nan, nan, nan, nan, 
  nan, nan, nan, nan, nan, nan, 
  nan
};
}
