#pragma once
#include <array>
#include <cstddef>

namespace MinPhaseBank {
struct TapSet { const double* data; int length; int order; };

constexpr std::array<double, 301> HB63_min = {
  nan, nan, nan, nan, nan, nan, 
  nan, nan, nan, nan, nan, nan, 
  nan, nan, nan, nan, nan, nan, 
  nan, nan, nan, nan, nan, nan, 
  nan, nan, nan, nan, nan, nan, 
  nan, nan, nan, nan, nan, nan, 
  nan, nan, nan, nan, nan, nan, 
  nan, nan, nan, nan, nan, nan, 
  nan, nan, nan, nan, nan, nan, 
  nan, nan, nan, nan, nan, nan, 
  nan, nan, nan, nan, nan, nan, 
  nan, nan, nan, nan, nan, nan, 
  nan, nan, nan, nan, nan, nan, 
  nan, nan, nan, nan, nan, nan, 
  nan, nan, nan, nan, nan, nan, 
  nan, nan, nan, nan, nan, nan, 
  nan, nan, nan, nan, nan, nan, 
  nan, nan, nan, nan, nan, nan, 
  nan, nan, nan, nan, nan, nan, 
  nan, nan, nan, nan, nan, nan, 
  nan, nan, nan, nan, nan, nan, 
  nan, nan, nan, nan, nan, nan, 
  nan, nan, nan, nan, nan, nan, 
  nan, nan, nan, nan, nan, nan, 
  nan, nan, nan, nan, nan, nan, 
  nan, nan, nan, nan, nan, nan, 
  nan, nan, nan, nan, nan, nan, 
  nan, nan, nan, nan, nan, nan, 
  nan, nan, nan, nan, nan, nan, 
  nan, nan, nan, nan, nan, nan, 
  nan, nan, nan, nan, nan, nan, 
  nan, nan, nan, nan, nan, nan, 
  nan, nan, nan, nan, nan, nan, 
  nan, nan, nan, nan, nan, nan, 
  nan, nan, nan, nan, nan, nan, 
  nan, nan, nan, nan, nan, nan, 
  nan, nan, nan, nan, nan, nan, 
  nan, nan, nan, nan, nan, nan, 
  nan, nan, nan, nan, nan, nan, 
  nan, nan, nan, nan, nan, nan, 
  nan, nan, nan, nan, nan, nan, 
  nan, nan, nan, nan, nan, nan, 
  nan, nan, nan, nan, nan, nan, 
  nan, nan, nan, nan, nan, nan, 
  nan, nan, nan, nan, nan, nan, 
  nan, nan, nan, nan, nan, nan, 
  nan, nan, nan, nan, nan, nan, 
  nan, nan, nan, nan, nan, nan, 
  nan, nan, nan, nan, nan, nan, 
  nan, nan, nan, nan, nan, nan, 
  nan
};

constexpr std::array<double, 301> HB95_min = {
  nan, nan, nan, nan, nan, nan, 
  nan, nan, nan, nan, nan, nan, 
  nan, nan, nan, nan, nan, nan, 
  nan, nan, nan, nan, nan, nan, 
  nan, nan, nan, nan, nan, nan, 
  nan, nan, nan, nan, nan, nan, 
  nan, nan, nan, nan, nan, nan, 
  nan, nan, nan, nan, nan, nan, 
  nan, nan, nan, nan, nan, nan, 
  nan, nan, nan, nan, nan, nan, 
  nan, nan, nan, nan, nan, nan, 
  nan, nan, nan, nan, nan, nan, 
  nan, nan, nan, nan, nan, nan, 
  nan, nan, nan, nan, nan, nan, 
  nan, nan, nan, nan, nan, nan, 
  nan, nan, nan, nan, nan, nan, 
  nan, nan, nan, nan, nan, nan, 
  nan, nan, nan, nan, nan, nan, 
  nan, nan, nan, nan, nan, nan, 
  nan, nan, nan, nan, nan, nan, 
  nan, nan, nan, nan, nan, nan, 
  nan, nan, nan, nan, nan, nan, 
  nan, nan, nan, nan, nan, nan, 
  nan, nan, nan, nan, nan, nan, 
  nan, nan, nan, nan, nan, nan, 
  nan, nan, nan, nan, nan, nan, 
  nan, nan, nan, nan, nan, nan, 
  nan, nan, nan, nan, nan, nan, 
  nan, nan, nan, nan, nan, nan, 
  nan, nan, nan, nan, nan, nan, 
  nan, nan, nan, nan, nan, nan, 
  nan, nan, nan, nan, nan, nan, 
  nan, nan, nan, nan, nan, nan, 
  nan, nan, nan, nan, nan, nan, 
  nan, nan, nan, nan, nan, nan, 
  nan, nan, nan, nan, nan, nan, 
  nan, nan, nan, nan, nan, nan, 
  nan, nan, nan, nan, nan, nan, 
  nan, nan, nan, nan, nan, nan, 
  nan, nan, nan, nan, nan, nan, 
  nan, nan, nan, nan, nan, nan, 
  nan, nan, nan, nan, nan, nan, 
  nan, nan, nan, nan, nan, nan, 
  nan, nan, nan, nan, nan, nan, 
  nan, nan, nan, nan, nan, nan, 
  nan, nan, nan, nan, nan, nan, 
  nan, nan, nan, nan, nan, nan, 
  nan, nan, nan, nan, nan, nan, 
  nan, nan, nan, nan, nan, nan, 
  nan, nan, nan, nan, nan, nan, 
  nan
};

constexpr std::array<double, 301> HB127_min = {
  nan, nan, nan, nan, nan, nan, 
  nan, nan, nan, nan, nan, nan, 
  nan, nan, nan, nan, nan, nan, 
  nan, nan, nan, nan, nan, nan, 
  nan, nan, nan, nan, nan, nan, 
  nan, nan, nan, nan, nan, nan, 
  nan, nan, nan, nan, nan, nan, 
  nan, nan, nan, nan, nan, nan, 
  nan, nan, nan, nan, nan, nan, 
  nan, nan, nan, nan, nan, nan, 
  nan, nan, nan, nan, nan, nan, 
  nan, nan, nan, nan, nan, nan, 
  nan, nan, nan, nan, nan, nan, 
  nan, nan, nan, nan, nan, nan, 
  nan, nan, nan, nan, nan, nan, 
  nan, nan, nan, nan, nan, nan, 
  nan, nan, nan, nan, nan, nan, 
  nan, nan, nan, nan, nan, nan, 
  nan, nan, nan, nan, nan, nan, 
  nan, nan, nan, nan, nan, nan, 
  nan, nan, nan, nan, nan, nan, 
  nan, nan, nan, nan, nan, nan, 
  nan, nan, nan, nan, nan, nan, 
  nan, nan, nan, nan, nan, nan, 
  nan, nan, nan, nan, nan, nan, 
  nan, nan, nan, nan, nan, nan, 
  nan, nan, nan, nan, nan, nan, 
  nan, nan, nan, nan, nan, nan, 
  nan, nan, nan, nan, nan, nan, 
  nan, nan, nan, nan, nan, nan, 
  nan, nan, nan, nan, nan, nan, 
  nan, nan, nan, nan, nan, nan, 
  nan, nan, nan, nan, nan, nan, 
  nan, nan, nan, nan, nan, nan, 
  nan, nan, nan, nan, nan, nan, 
  nan, nan, nan, nan, nan, nan, 
  nan, nan, nan, nan, nan, nan, 
  nan, nan, nan, nan, nan, nan, 
  nan, nan, nan, nan, nan, nan, 
  nan, nan, nan, nan, nan, nan, 
  nan, nan, nan, nan, nan, nan, 
  nan, nan, nan, nan, nan, nan, 
  nan, nan, nan, nan, nan, nan, 
  nan, nan, nan, nan, nan, nan, 
  nan, nan, nan, nan, nan, nan, 
  nan, nan, nan, nan, nan, nan, 
  nan, nan, nan, nan, nan, nan, 
  nan, nan, nan, nan, nan, nan, 
  nan, nan, nan, nan, nan, nan, 
  nan, nan, nan, nan, nan, nan, 
  nan
};

constexpr TapSet registry[] = {
  { HB63_min.data(), (int)HB63_min.size(), 63 },
  { HB95_min.data(), (int)HB95_min.size(), 95 },
  { HB127_min.data(), (int)HB127_min.size(), 127 },
};
constexpr int registryCount = (int)(sizeof(registry)/sizeof(registry[0]));
}
